<html>
    <body>
        <?php 
            /*
                return view('/Menus/prueba')
            ->with('fechas',$fecha)
            ->with('mensualidades',$mensualidades)
            ->with('intereses',$intereses)
            ->with('diasRetraso',$diasRetraso)
            ->with('estados',$estado);
            */
            for($cont=0;$cont<count($fechas);$cont++){
                echo($fechas[$cont]."<->".$mensualidades[$cont]."<->".$intereses[$cont]
                     ."<->".$diasRetraso[$cont]."<->".$estados[$cont]);
                echo("<br/>");
            }
        echo("<h1>pruebas</h1>");
                echo($pruebas);
        ?>
        <br>
    </body>
</html>